name: 'Close stale PRs'
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-pr-message: 'This PR is stale because it has been open 28 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-label: stale
          days-before-stale: 28
          days-before-close: 5
